application/models.py
from sqlalchemy import Column, Integer, Numeric, String, Index, DateTime, func
from sqlalchemy.orm import declarative_base
from sqlalchemy_utils import ChoiceType

from constants import Currency

Base = declarative_base()


class Transaction(Base):
    """Table to store transactions"""

    __tablename__ = "transaction"

    id = Column(Integer, primary_key=True, index=True)
    amount = Column(Numeric, nullable=False)
    currency = Column(ChoiceType(Currency, impl=Integer()), nullable=False)
    description = Column(String(200), nullable=False)

    # by default in UTC zone
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)


Index("transaction_currency_idx", Transaction.currency)

application/app.py
from flask import Flask

from config import ApplicationConfig
from blueprints import root, error_handler, transactions
from middleware import Middleware


def get_application() -> Flask:
    """Creates an application"""

    config = ApplicationConfig()
    app = Flask(__name__)

    app.config.update(**config.dict())
    app.user_config = config

    app.wsgi_app = Middleware(app.wsgi_app)
    return app


app = get_application()

# register blueprints
app.register_blueprint(error_handler, url_prefix="/")
app.register_blueprint(root, url_prefix="/")
app.register_blueprint(transactions, url_prefix="/transactions")


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000)

application/blueprints/__init__.py
from application.blueprints.root import root
from application.blueprints.error_handler import error_handler
from application.blueprints.transactions import transactions

application/blueprints/error_handler.py
from flask import Blueprint, render_template
from http import HTTPStatus

error_handler = Blueprint("error_handler", __name__)


@error_handler.app_errorhandler(HTTPStatus.NOT_FOUND)
def page_not_found(error):
    """Handles 404 error"""

    return render_template("errors/404.html")


@error_handler.app_errorhandler(HTTPStatus.METHOD_NOT_ALLOWED)
def page_not_found(error):
    """Handles 405 error"""

    return render_template("errors/405.html")


@error_handler.app_errorhandler(HTTPStatus.INTERNAL_SERVER_ERROR)
def server_internal_error(error):
    """Handles 500 error"""

    # Houston, we have a problem

application/blueprints/root.py
from flask import Blueprint, render_template


root = Blueprint("base", __name__)


@root.route("/")
def main():
    """Root method of the app"""
    return render_template("index.html")

application/blueprints/transactions.py
import math

from flask import Blueprint, render_template, request, redirect, url_for
from sqlalchemy import func

from constants import HTTPMethods, TransactionFields, Currency, PAGE_SIZE
from db import DBEngine
from exceptions import FieldNotFound
from models import Transaction

transactions = Blueprint("transactions", __name__)


@transactions.route("/add", methods=[HTTPMethods.GET, HTTPMethods.POST])
def add_transaction():
    if request.method == HTTPMethods.POST:
        try:
            amount = request.form[TransactionFields.VALUE]
            currency = request.form[TransactionFields.CURRENCY]
            description = request.form[TransactionFields.DESCRIPTION]
        except KeyError as error:
            raise FieldNotFound(f"Filed form wasn't found. {error = }")

        transaction = Transaction(
            amount=amount, currency=currency, description=description)

        with DBEngine().session_scope() as session:
            session.add(transaction)

        return redirect(url_for("base.main"))

    return render_template("transactions/add.html", currencies=Currency.get_currencies())


@transactions.route("/list/", defaults={"page": 1})
@transactions.route("/list/<int:page>")
def get_transactions(page: int):

    with DBEngine().session_scope() as session:
        query_result = session.query(Transaction).offset((page - 1) * PAGE_SIZE)\
            .limit(PAGE_SIZE).all()

        count = session.query(func.count(Transaction.id)).scalar()
        session.expunge_all()

    params = dict(
        transactions=query_result,
        active_page=page,
        pages=math.ceil(count / PAGE_SIZE),
        page_size=PAGE_SIZE,
    )

    return render_template("transactions/list.html", **params)


@transactions.route("/<int:transaction_id>")
def get_transaction(transaction_id: int):
    print(transaction_id)
    with DBEngine().session_scope() as session:
        transaction = session.query(Transaction).get(transaction_id)
        session.expunge_all()

    return render_template("transactions/item.html", transaction=transaction)

application/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
    {% include "base/head.html" %}
    <body>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-12 col-lg-11 col-xl-10">

                    {% block content %}{% endblock %}

                </div>
            </div>
        </div>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
<!--        <script src="{{ url_for('static', filename='scripts.js') }}"></script>-->
    </body>
</html>

application/templates/base/head.html
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Flask template</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon/favicon.ico') }}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>

    <!-- Google fonts-->
    <!-- <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />-->
    <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />-->

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{{ url_for('static', filename='styles.css') }}" rel="stylesheet" />
</head>

application/templates/index.html
{% extends "base/base.html" %}

{% block content %}

<div class="container">
    <div class="transactions-container">
        <div>
            <a href="{{ url_for('transactions.add_transaction')}}">
                <button class="button">Add transaction</button>
            </a>
        </div>

        <div>
            <a href="{{ url_for('transactions.get_transactions')}}">
                <button class="button">View all transactions</button>
            </a>
        </div>
    </div>
</div>

{% endblock %}

application/templates/transactions/add.html
{% extends "base/base.html" %}

{% block content %}

<form method="post">
    <label for="value">Value</label>
    <input type="number" step=0.001 name="value" placeholder="Enter value"/>
    <br><br>

    <label for="currency">Currency</label>
    <select id="currency" name="currency">
        {% for currency in currencies %}
            <option value="{{ currency }}"> {{ currency }}</option>
        {% endfor %}
    </select>
    <br><br>

    <label for="content">Description</label><br>
    <textarea name="description" placeholder="Description" rows="3" cols="50"></textarea>
    <br><br>

    <button type="submit">Submit</button>
</form>

{% endblock %}

application/templates/transactions/item.html
{% extends "base/base.html" %}

{% block content %}

<form method="post">
    <p>Amount: {{ transaction.amount }}</p>
    <p>Currency: {{ transaction.currency.value }}</p>
    <p>Description: {{ transaction.description }}</p>
    <p>Created at: {{ transaction.created_at }}</p>
</form>



{% endblock %}

application/templates/transactions/list.html
{% extends "base/base.html" %}

{% block content %}

<div class="table-container">
    <table>
        <thead>
        <tr>
            <th>Number</th>
            <th>Amount</th>
            <th>Currency</th>
            <th>Description</th>
            <th>Created at</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for transaction in transactions %}
            <tr class="cell">
                <th>{{ loop.index }}</th>
                <td>{{ transaction.amount }}</td>
                <td>{{ transaction.currency.value }}</td>
                <td>{{ transaction.description | truncate(30, True) }}</td>
                <td>{{ transaction.created_at }}</td>
                <td>
                    <a class="table-button" href="{{ url_for('transactions.get_transaction', transaction_id=loop.index + page_size * (active_page-1))}}">Open</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="pagination">
        {% if active_page - 1 > 0 %}
            <a href="{{ url_for('transactions.get_transactions', page=active_page-1)}}">&laquo;</a>
        {% else %}
            <a href="{{ url_for('transactions.get_transactions', page=active_page)}}">&laquo;</a>
        {% endif %}

        {% for page in range(1, pages + 1) %}
            {% if loop.index == active_page %}
                <a class="active" href="#">{{ page }}</a>
            {% else %}
                <a href="{{ url_for('transactions.get_transactions', page=page)}}">{{ page }}</a>
            {% endif %}
        {% endfor %}

        {% if active_page + 1 <= pages %}
            <a href="{{ url_for('transactions.get_transactions', page=active_page+1)}}">&raquo;</a>
        {% else %}
            <a href="{{ url_for('transactions.get_transactions', page=active_page)}}">&raquo;</a>
        {% endif %}
    </div>
</div>


{% endblock %}